apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton
spec:
  params:
  - name: docker-image
    description: Name of the Docker image to build and push
    type: string
  workspaces:
  - name: source
    description: Workspace containing the source code
  steps:
  - name: build-image
    image: docker
    workingDir: $(workspaces.source.path)
    script: |
      docker build -t $(params.docker-image) .
  - name: push-image
    image: docker
    workingDir: $(workspaces.source.path)
    script: |
      docker push $(params.docker-image)
