apiVersion: v1
kind: Service
metadata:
  name: rails-app
  namespace: budget
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000 # Choose a port between 30000-32767
  selector:
    app: rails
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  namespace: budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - name: rails-app
          image: ashniike/budget-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: myapp_production
            - name: POSTGRES_HOST
              value: postgres
          volumeMounts:
            - name: rails-data
              mountPath: /app
      volumes:
        - name: rails-data
          emptyDir: {}
